{% set name = "datar" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/datar-{{ version }}.tar.gz
  sha256: f8997bb79089757e14810dc6537b7c83e59da25223b9d58d931f38a8c7fa5bd4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6,<4.0
    - poetry >=1.1.12
  run:
    - diot >=0.1.1,<0.2.0
    - pandas >=1.2,<2.0
    - pipda >=0.4.5,<0.5.0
    - python >=3.6,<4.0
    - python-slugify >=5.0.2,<6.0.0
    - scipy >=1.6,<2.0
    - wcwidth >=0.2,<0.3

test:
  imports:
    - datar
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pwwang/datar
  summary: Port of dplyr and other related R packages in python, using pipda.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AhmedAliStats
