{% set name = "datar" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/datar-{{ version }}.tar.gz
  sha256: b9250518e254e73c009c206bf935d6b8ece8b270e61222d5b8e6b173bd40a624

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7,<4.0
    - poetry >=1.1.12
  run:
    - diot >=0.1.1,<0.2.0
    - pandas >=1.3,<2.0
    - pdtypes >=0.0.4,<0.0.5
    - pipda >=0.5.7,<0.6.0
    - python >=3.7,<4.0
    - python-slugify >=6,<7
    - scipy >=1.6,<2.0
    - toml >=0.10.2,<0.11.0
    - wcwidth >=0.2,<0.3

test:
  imports:
    - datar
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pwwang/datar
  summary: Port of dplyr and other related R packages in python, using pipda.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AhmedAliStats
